pipeline:
  install-v:
    image: 'alpine:latest'
    commands:
      - apk update
      - apk add --no-cache git make build-base
      - make customv

  lint:
    image: 'alpine:latest'
    commands:
      - jjr-v/v lint

  build:
    image: 'alpine:latest'
    commands:
      - jjr-v/v vieter

