# This file contains settings used during development
api_key = "test"
data_dir = "data"
pkg_dir = "data/pkgs"
log_level = "DEBUG"
default_arch = "x86_64"
arch = "x86_64"

address = "http://localhost:8000"

# global_schedule = '* *'
api_update_frequency = 2
image_rebuild_frequency = 1
max_concurrent_builds = 3
max_log_age = 64
log_removal_schedule = '*/2 *'
