# These builds are not important for the project, but might be valuable for
# fixing bugs in the V compiler.

platform: linux/amd64
branches:
  exclude: [master, dev]

pipeline:
  autofree:
    image: 'chewingbever/vlang:latest'
    pull: true
    group: 'build'
    commands:
      - make autofree
      - readelf -d afvieter
      - du -h afvieter
    when:
      event: push

  skip-unused:
    image: 'chewingbever/vlang:latest'
    pull: true
    group: 'build'
    commands:
      - make skip-unused
      - readelf -d suvieter
      - du -h suvieter
    when:
      event: push

  skip-unused-static:
    image: 'chewingbever/vlang:latest'
    pull: true
    environment:
      - LDFLAGS=-lz -lbz2 -llzma -lexpat -lzstd -llz4 -static
    group: 'build'
    commands:
      - make skip-unused
      - readelf -d suvieter
      - du -h suvieter
    when:
      event: push
