# These checks already get performed on the feature branches
branches:
  exclude: [ main, dev ]
platform: linux/arm64

pipeline:
  vieter:
    image: 'chewingbever/vlang:latest'
    group: 'build'
    commands:
      - make vieter

  debug:
    image: 'chewingbever/vlang:latest'
    group: 'build'
    commands:
      - make debug

  prod:
    image: 'chewingbever/vlang:latest'
    environment:
      - LDFLAGS=-lz -lbz2 -llzma -lexpat -lzstd -llz4 -static
    group: 'build'
    commands:
      - make prod
      # Make sure the binary is actually static
      - [ "$(readelf -d pvieter) | grep NEEDED | wc -l" = 0 ]
