# branches: dev
platform: linux/amd64

pipeline:
  publish:
    image: woodpeckerci/plugin-docker-buildx
    secrets: [ docker_username, docker_password ]
    settings:
      repo: chewingbever/vlang
      tag: latest
      dockerfile: Dockerfile.builder
      platforms: [ linux/arm/v7, linux/arm64/v8, linux/amd64 ]
    when:
      event: push
      path: Dockerfile.builder
