# These checks already get performed on the feature branches
branches:
  exclude: [ main, dev ]

pipeline:
  vieter:
    image: 'chewingbever/vlang:latest'
    pull: true
    group: 'build'
    environment:
      - LDFLAGS=-lz -lbz2 -llzma -lexpat -lzstd -llz4 -static
    commands:
      - make vieter

  debug:
    image: 'chewingbever/vlang:latest'
    pull: true
    environment:
      - LDFLAGS=-lz -lbz2 -llzma -lexpat -lzstd -llz4 -static
    group: 'build'
    commands:
      - make debug

  prod:
    image: 'chewingbever/vlang:latest'
    pull: true
    environment:
      - LDFLAGS=-lz -lbz2 -llzma -lexpat -lzstd -llz4 -static
    group: 'build'
    commands:
      - make prod
