# Yeah so this only works on tags so we'll worry about this later
platform: linux/amd64
branches: main
depends_on:
  - build

# We need the entire repo in order for the release names to work
skip_clone: true

pipeline:
  prepare:
    image: 'chewingbever/vlang:latest'
    pull: true
    secrets: [ s3_username, s3_password ]
    commands:
      - mc alias set s3/ https://s3.rustybever.be "$S3_USERNAME" "$S3_PASSWORD"
      - mc cp -r "s3/vieter/commits/$CI_COMMIT_SHA" .
    when:
      event: tag

  release:
    image: 'plugins/gitea-release'
    secrets:
      - gitea_release_api_key
    settings:
      base_url: https://git.rustybever.be
      files: ${CI_COMMIT_SHA}/*
      checksum:
        - md5
        - sha256
      prerelease: true
      title: ${CI_COMMIT_TAG}
    when:
      event: tag
