# These checks already get performed on the feature branches
branches:
  exclude: [ main ]
platform: 'linux/amd64'

pipeline:
  lint:
    image: 'chewingbever/vlang:latest'
    pull: true
    commands:
      - make lint
    when:
      event: [ push, pull_request ]
