branches: [main, dev]
platform: linux/amd64

pipeline:
  dev:
    image: woodpeckerci/plugin-docker-buildx
    secrets: [ docker_username, docker_password ]
    settings:
      dockerfile: Dockerfile.ci
      repo: chewingbever/vieter
      tag: dev
      platforms: [ linux/arm/v7, linux/arm64/v8, linux/amd64 ]
      args:
        - CI_COMMIT_SHA
    when:
      event: push
      branch: dev

  release:
    image: woodpeckerci/plugin-docker-buildx
    secrets: [ docker_username, docker_password ]
    settings:
      repo: chewingbever/vieter
      tag:
        - latest
        - $CI_COMMIT_TAG
      platforms: [ linux/arm/v7, linux/arm64/v8, linux/amd64 ]
    when:
      event: tag
      branch: main

depends_on:
  - builder
  - build
