# branches: [main, dev]
platform: linux/amd64

pipeline:
  dev:
    image: woodpeckerci/plugin-docker-buildx
    secrets: [ docker_username, docker_password ]
    settings:
      repo: chewingbever/vieter
      tag: dev
      platforms: [ linux/arm/v7, linux/arm64/v8, linux/amd64 ]
    when:
      event: push
      branch: dev

  release:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    settings:
      repo: chewingbever/vieter
      tag:
        - latest
        - $CI_COMMIT_TAG
      mtu: 1000
    when:
      event: tag
      branch: main

# depends_on:
#   - builder
