matrix:
  PLATFORM:
    - linux/amd64
    - linux/arm64

platform: ${PLATFORM}

pipeline:
  test:
    image: 'chewingbever/vlang:latest'
    pull: true
    commands:
      - make test
    when:
      event: push
