variables:
  - &vlang_image 'git.rustybever.be/chewing_bever/vlang:0.3.2'

# These checks already get performed on the feature branches
branches:
  exclude: [ main ]
platform: 'linux/amd64'

pipeline:
  lint:
    image: *vlang_image
    pull: true
    commands:
      - make lint
    when:
      event: [ pull_request ]
